std = "lua52"
codes = true
max_line_length = false
allow_defined_top = true

exclude_files = {
   ".ccbrowser/**",
   "dist/**"
}

ignore = {
   "131"
}

globals = {
   "_HOST",
   "_CC_DEFAULT_SETTINGS",
   "cc",
   "colors",
   "colours",
   "commands",
   "disk",
   "fs",
   "gps",
   "help",
   "http",
   "keys",
   "multishell",
   "paintutils",
   "parallel",
   "peripheral",
   "pocket",
   "rednet",
   "redstone",
   "rs",
   "settings",
   "shell",
   "sleep",
   "term",
   "textutils",
   "turtle",
   "vector",
   "window",
   "printError",
   "ANIMATION_TICK_SECONDS",
   "BROWSER_LOGS_DIR",
   "browserFavorites",
   "browserHistory",
   "browserSettings",
   "buildDocument",
   "CC_BROWSER_BASE_DIR",
   "clamp",
   "clampControlInnerWidth",
   "cloneControlStyle",
   "COLOR_NAME_TO_VALUE",
   "content",
   "createEmptyLine",
   "decodeEntities",
   "default",
   "displayManager",
   "ensureContrastingForeground",
   "escapeHtml",
   "fetchTextResource",
   "formControls",
   "getfenv",
   "getHeader",
   "hasBooleanAttr",
   "HIGH_USAGE_COOLDOWN_SECONDS",
   "HIGH_USAGE_FRAME_THRESHOLD_LOADING_MS",
   "HIGH_USAGE_FRAME_THRESHOLD_MS",
   "HIGH_USAGE_STRIKE_LIMIT",
   "insertIntoFormControl",
   "INTERNAL_MONITOR_ID",
   "layoutUi",
   "loadstring",
   "LOG_LEVEL_ALIASES",
   "LOG_LEVEL_NAMES",
   "logWriteBusy",
   "looksLikeHtml",
   "makeControlKey",
   "makeErrorPage",
   "maybeYield",
   "NATIVE_TERM",
   "network",
   "nodeTextContent",
   "normalizeInputUrl",
   "normalizePaletteColorName",
   "PAUSED_APPLET_EVENT_MAX",
   "PAUSED_APPLET_FLUSH_PER_FRAME",
   "printing",
   "read",
   "registerControl",
   "resolveControlFormId",
   "resolveRelativeUrl",
   "sandbox",
   "setfenv",
   "startsWith",
   "SUPPORTED_COLOR_NAMES",
   "SUPPORTED_SETTING_COLOR_ERROR_TEXT",
   "tabCloseIndexAt",
   "tabIndexAt",
   "transformText",
   "trim",
   "unpack",
   "utf8",
   "withCursorMarker",
   "write"
}

read_globals = {
   os = {
      fields = {
         "version",
         "getComputerID",
         "getComputerLabel",
         "pullEvent",
         "pullEventRaw",
         "queueEvent",
         "startTimer",
         "cancelTimer",
         "setAlarm",
         "cancelAlarm",
         "shutdown",
         "reboot",
         "epoch",
         "day"
      }
   }
}
