name: CI/CD

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Lint Lua sources
        uses: lunarmodules/luacheck@v1
        with:
          args: '--only 0 -- .'

      - name: Print lint results
        uses: lunarmodules/luacheck@v1
        continue-on-error: true
